baseURL = 'https://www.skypirate.cloud'
languageCode = 'en-us'
title = 'Terok Noir'
theme = 'nightfall'
pluralizelisttitles = false
relativeURLs = true
enableGitInfo = true
enableRobotsTXT = true
timeZone = 'America/Vancouver'
buildDrafts = false
buildFuture = false
buildExpired = true
readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[frontmatter]
  date = [':git', ':fileModTime', ":default"]
  lastmod = [':git', ':fileModTime']


[menu]
  [[menu.header]]
    name = "books"
    weight = 1
    url = "books"
  [[menu.header]]
    name = "cinema"
    weight = 2
    url = "cinema"
  [[menu.header]]
    name = "sounds"
    weight = 0
    url = "sounds"
  [[menu.header]]
    name = "linux"
    weight = 3
    url = "linux"

[params]
user = "elim.garak"
hostname = "obsidian-order"
footerHtml = '© 2024, Princeton Strong - All rights reserved. Powered by Hugo and Nightfall.'
dateFormat = "Jan 02, 2006 3:04 PM Z07:00"
  [params.author]
    name = "Terok Noir"  # Website and RSS feed author
    email = "princeton.strong@outlook.com"  # RSS feed email address

[[params.social]]
key = 0
name = "github"
url = "https://github.com/borninthedark"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 1
name = "email"
url = "mailto:princeton.strong@outlook.com"
aria = "My e-Mail Address"

[module]
[[module.imports]]
  path = 'github.com/LordMathis/hugo-theme-nightfall'
